 database:
    {
    'user': 'postgres',
    'password': '10011992',
    'host': '127.0.0.1',
    'port': '5432',
    'database_name': 'bakery_db',
   }

 categories:
   - 'Напитки'
   - 'Сладкая выпечка'
   - 'Торты'


 products: [
     {
     'name': 'Американо',
     'description': 'Обычный кофе',
     'foto': 'photo-219109543_457239022',
     'category': 'Напитки',
    },
   {
       'name': 'Капучино',
       'description': 'Кофе с молоком',
       'foto': 'photo-219109543_457239020',
       'category': 'Напитки',
   },
   {
       'name': 'Эспрессо',
       'description': 'Крепкий кофе',
       'foto': 'photo-219109543_457239021',
       'category': 'Напитки',
   },
   {
       'name': 'Кекс',
       'description': 'Творожный кекс в духовке',
       'foto': 'photo-219109543_457239024',
       'category': 'Сладкая выпечка',
   },
   {
       'name': 'Шарлотка',
       'description': 'Пирог с яблоками',
       'foto': 'photo-219109543_457239023',
       'category': 'Сладкая выпечка',
   },
   {
       'name': 'Заливной пирог',
       'description': 'Пирог с черникой',
       'foto': 'photo-219109543_457239025',
       'category': 'Сладкая выпечка',
   },
   {
       'name': 'Красный бархат',
       'description': 'Американский шоколадный торт с сырным кремом',
       'foto': 'photo-219109543_457239027',
       'category': 'Торты',
   },
   {
       'name': 'Эстерхази',
       'description': 'Миндально-шоколадный торт',
       'foto': 'photo-219109543_457239026',
       'category': 'Торты',
   },
   {
       'name': 'Захер',
       'description': 'Шоколадный торт',
       'foto': 'photo-219109543_457239028',
       'category': 'Торты',
   },
 ]